#!/usr/bin/env python3
"""Generate EN/FR LaTeX tables from the archived controlled-run summary."""

from __future__ import annotations

import json
import statistics
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SUMMARY = ROOT / "artifacts/h200-controlled-replications/summary.json"
OUT = ROOT / "generated"


def number(value: float, *, decimal: str = ".", digits: int = 6) -> str:
    return f"{value:.{digits}f}".replace(".", decimal)


def integer(value: float, *, french: bool = False) -> str:
    separator = "~" if french else ","
    return f"{round(value):,}".replace(",", separator)


def render(data: dict[str, object], *, french: bool) -> str:
    decimal = "," if french else "."
    runs = data["runs"]
    assert isinstance(runs, list)
    by_arch = {
        architecture: {
            int(run["seed"]): run
            for run in runs
            if run["architecture"] == architecture
        }
        for architecture in ("gqa", "wrv-lexical-off")
    }
    agg = data["aggregate"]
    assert isinstance(agg, dict)
    gqa = agg["gqa"]
    wrv = agg["wrv-lexical-off"]
    delta = agg["paired_delta"]
    assert isinstance(gqa, dict) and isinstance(wrv, dict) and isinstance(delta, dict)
    throughput_sd = {
        architecture: statistics.stdev(
            float(run["median_tok_s"]) for run in by_arch[architecture].values()
        )
        for architecture in by_arch
    }
    caption_loss = (
        "Loss tenue à part appariée par seed. Chaque valeur est l'évaluation "
        "finale à l'étape 3~000 sur 1~048~576 tokens."
        if french
        else "Matched held-out loss by seed. Lower is better. Each value is the "
        "final step-3,000 evaluation over 1,048,576 held-out tokens."
    )
    caption_speed = (
        "Débit d'entraînement sur un H200. Chaque seed contribue sa médiane "
        "après warmup et exclusion des pauses d'évaluation/checkpoint ; moyenne "
        "et écart-type sont calculés entre seeds."
        if french
        else "Training throughput on one H200. Each seed contributes its post-warmup "
        "median after evaluation/checkpoint stalls are excluded; the table reports "
        "the mean and sample SD across seeds."
    )
    mean_label = "Moyenne" if french else "Mean"
    sd_label = "Écart-type" if french else "Sample SD"
    mechanism = "Mécanisme" if french else "Mechanism"
    throughput = "Débit moyen" if french else "Mean train tok/s"
    rows = []
    for seed in sorted(by_arch["gqa"]):
        gqa_loss = float(by_arch["gqa"][seed]["eval_loss"])
        wrv_loss = float(by_arch["wrv-lexical-off"][seed]["eval_loss"])
        rows.append(
            f"{seed} & {number(gqa_loss, decimal=decimal)} & "
            f"\\textbf{{{number(wrv_loss, decimal=decimal)}}} & "
            f"${number(wrv_loss - gqa_loss, decimal=decimal)}$ \\\\"
        )
    return f"""% Generated by scripts/generate_controlled_tables.py; do not edit.
\\begin{{table}}[t]
\\caption{{{caption_loss}}}
\\label{{tab:h200-controlled}}
\\centering
\\small
\\begin{{tabular}}{{lrrr}}
\\toprule
Seed & GQA & W/R/V & W/R/V $-$ GQA \\\\
\\midrule
{chr(10).join(rows)}
\\midrule
{mean_label} & {number(float(gqa['eval_loss_mean']), decimal=decimal)} & \\textbf{{{number(float(wrv['eval_loss_mean']), decimal=decimal)}}} & ${number(float(delta['mean']), decimal=decimal)}$ \\\\
{sd_label} & {number(float(gqa['eval_loss_sample_sd']), decimal=decimal)} & {number(float(wrv['eval_loss_sample_sd']), decimal=decimal)} & {number(float(delta['sample_sd']), decimal=decimal)} \\\\
\\bottomrule
\\end{{tabular}}
\\end{{table}}

\\begin{{table}}[t]
\\caption{{{caption_speed}}}
\\label{{tab:h200-throughput}}
\\centering
\\small
\\begin{{tabular}}{{lrr}}
\\toprule
{mechanism} & {throughput} $\\uparrow$ & {sd_label} \\\\
\\midrule
GQA & \\textbf{{{integer(float(gqa['median_tok_s_mean']), french=french)}}} & {integer(throughput_sd['gqa'], french=french)} \\\\
{'W/R/V contextuel' if french else 'Contextual W/R/V'} & {integer(float(wrv['median_tok_s_mean']), french=french)} & {integer(throughput_sd['wrv-lexical-off'], french=french)} \\\\
\\bottomrule
\\end{{tabular}}
\\end{{table}}
"""


def main() -> None:
    data = json.loads(SUMMARY.read_text())
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "controlled_tables_en.tex").write_text(render(data, french=False))
    (OUT / "controlled_tables_fr.tex").write_text(render(data, french=True))


if __name__ == "__main__":
    main()
