[program:tr_hash_voc_train]
environment=PROC_NAME="%(program_name)s"
command=/workspace/complexity-framework/scripts/vast_train_voc.sh
directory=/workspace/complexity-framework
autostart=false
autorestart=false
startsecs=1
stopsignal=INT
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
