"""Convert a ``token_routed`` checkpoint to the canonical ``tr_hash_engine``.

``TokenRoutedMLP`` (the historical, feature-complete dispatch implementation)
and ``TRHashEngineMLP`` (the canonical path for new models, see
:mod:`complexity.tr_hash`) store their per-expert weights in the same
``[num_experts, hidden_size, expert_width]`` / ``[num_experts, expert_width,
hidden_size]`` layout — only the parameter names and the module nesting
differ. This module renames the checkpoint's tensors accordingly and,
critically, transplants the *exact trained* token->expert routing table
(``topk_token_to_expert`` -> ``engine.route_table``) rather than letting
``TRHashEngine`` regenerate its own from ``routing_strategy`` — the two
implementations' route-table constructions are different algorithms and are
not guaranteed to agree, so regenerating would silently pair an expert's
trained weights with a different set of tokens than it was trained on.

Config handling works on raw ``dict``s (e.g. a parsed ``config.json``), never
on a constructed :class:`ModelConfig` with ``mlp_type="token_routed"`` —
that value is rejected by ``ModelConfig.__post_init__``'s guardrail (the
framework no longer builds models with the historical dispatch
implementation), so a checkpoint's old config can only be read, patched, and
handed to :class:`ModelConfig` *after* the swap to ``tr_hash_engine``.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Dict, Tuple, Union

import torch

from ..config import ModelConfig

_MLP_KEY = re.compile(r"^(?P<prefix>layers\.(?P<layer>\d+)\.mlp)\.(?P<rest>.+)$")

_RENAME = {
    "gate_proj_w": "engine.expert_gate",
    "up_proj_w": "engine.expert_up",
    "down_proj_w": "engine.expert_down",
    "shared_gate.weight": "engine.shared_gate.weight",
    "shared_up.weight": "engine.shared_up.weight",
    "shared_down.weight": "engine.shared_down.weight",
}
# Regenerated by TRHashEngine itself (deterministic given config) or has no
# tr_hash_engine equivalent — dropped rather than mapped.
_DROPPED_SUFFIXES = (
    "token_to_expert",
    "pair_hash_route_codes",
    "pair_hash_expert_pairs",
    "lsh_planes",
    "lsh_bucket_to_expert",
    "lsh_threshold",
    "last_shared_rms",
    "last_routed_rms",
)
# Carried separately (not through the state dict) via TRHashEngine.load_route_table
# so fused-CUDA pair metadata is recompiled to match, instead of going stale.
_ROUTE_TABLE_SUFFIX = "topk_token_to_expert"

_CONVERTIBLE_MLP_TYPES = ("token_routed", "sort_split", "sort_split_moe")


def convert_token_routed_state_dict(
    state_dict: Dict[str, torch.Tensor],
) -> Tuple[Dict[str, torch.Tensor], Dict[int, torch.Tensor]]:
    """Rename a token_routed state dict's MLP tensors to tr_hash_engine's layout.

    Returns ``(converted_state_dict, route_tables)`` where ``route_tables``
    maps layer index -> the layer's trained ``[top_k, vocab_size]`` routing
    table. Install those with ``TRHashEngine.load_route_table`` after the
    model is constructed and ``converted_state_dict`` is loaded — the route
    table is deliberately not part of the returned state dict.
    """

    converted: Dict[str, torch.Tensor] = {}
    route_tables: Dict[int, torch.Tensor] = {}
    for key, value in state_dict.items():
        match = _MLP_KEY.match(key)
        if not match:
            converted[key] = value
            continue
        rest = match.group("rest")
        if rest == _ROUTE_TABLE_SUFFIX:
            route_tables[int(match.group("layer"))] = value
            continue
        if any(rest == suffix or rest.endswith("." + suffix) for suffix in _DROPPED_SUFFIXES):
            continue
        if rest in _RENAME:
            converted[f"{match.group('prefix')}.{_RENAME[rest]}"] = value
            continue
        # Unrecognized token_routed-only tensor (e.g. an ablation feature
        # tr_hash_engine has no equivalent for): surface it instead of
        # silently dropping trained weights.
        raise ValueError(
            f"don't know how to convert token_routed MLP tensor {key!r}: "
            "no tr_hash_engine equivalent is registered for it"
        )
    return converted, route_tables


def convert_token_routed_config(config: Dict[str, Any]) -> ModelConfig:
    """Build a ``tr_hash_engine`` :class:`ModelConfig` from a raw config dict.

    Takes the checkpoint's parsed ``config.json`` (a plain ``dict``), not a
    constructed :class:`ModelConfig` — ``ModelConfig(mlp_type="token_routed")``
    is itself rejected by the mlp_type guardrail, so the swap has to happen
    before the dict ever becomes a ``ModelConfig``.
    """

    mlp_type = config.get("mlp_type")
    if mlp_type not in _CONVERTIBLE_MLP_TYPES:
        raise ValueError(
            "convert_token_routed_config expects a config dict with "
            f"mlp_type one of {_CONVERTIBLE_MLP_TYPES}, got {mlp_type!r}"
        )
    patched = dict(config)
    patched["mlp_type"] = "tr_hash_engine"
    return ModelConfig.from_dict(patched)


def convert_token_routed_checkpoint(
    state_dict: Dict[str, torch.Tensor],
    config: Dict[str, Any],
) -> "torch.nn.Module":
    """Build the ``tr_hash_engine`` equivalent of a ``token_routed`` checkpoint.

    Takes the raw ``state_dict``/``config`` pair (e.g. loaded straight from a
    ``model.safetensors`` + ``config.json`` pair on disk) — the historical
    ``TokenRoutedMLP`` class doesn't need to be importable to run this.
    Constructs a fresh ``tr_hash_engine`` model, transplants the renamed
    weights, and installs each layer's exact trained routing table.
    """

    from ..models import ComplexityModel

    new_config = convert_token_routed_config(config)
    new_model = ComplexityModel(new_config)

    converted_state_dict, route_tables = convert_token_routed_state_dict(state_dict)
    missing, unexpected = new_model.load_state_dict(converted_state_dict, strict=False)
    # route_table/fused_route_codes/fused_expert_pairs are expected missing:
    # load_route_table (below) installs the trained route_table and
    # recompiles the fused metadata from it, so their freshly-constructed
    # (pre-injection) values would be wrong to load anyway.
    expected_missing_suffixes = (
        ".engine.route_table",
        ".engine.fused_route_codes",
        ".engine.fused_expert_pairs",
        ".rotary_emb.inv_freq",
    )
    unexplained_missing = [
        k for k in missing if not k.endswith(expected_missing_suffixes)
    ]
    if unexplained_missing or unexpected:
        raise RuntimeError(
            "token_routed -> tr_hash_engine conversion left mismatched keys: "
            f"missing={unexplained_missing}, unexpected={unexpected}"
        )

    for layer_idx, route_table in route_tables.items():
        new_model.layers[layer_idx].mlp.engine.load_route_table(route_table)

    return new_model


def convert_token_routed_checkpoint_dir(
    checkpoint_dir: Union[str, Path],
) -> "torch.nn.Module":
    """Load a ``token_routed`` HF-style checkpoint directory as a ``tr_hash_engine`` model.

    Expects ``config.json`` and ``model.safetensors`` (or ``pytorch_model.bin``)
    at ``checkpoint_dir``, same layout as :meth:`ComplexityModel.from_pretrained`.
    """

    import json

    checkpoint_dir = Path(checkpoint_dir)
    with open(checkpoint_dir / "config.json") as f:
        config = json.load(f)

    safetensors_path = checkpoint_dir / "model.safetensors"
    if safetensors_path.exists():
        from safetensors.torch import load_file

        state_dict = load_file(str(safetensors_path))
    else:
        state_dict = torch.load(
            checkpoint_dir / "pytorch_model.bin", map_location="cpu", weights_only=True
        )

    return convert_token_routed_checkpoint(state_dict, config)
